// v0.6 interaction layer. Four fixed tabs agreed with the product owner:
// Home = ordinary vibration & presets; Music = music-driven vibration;
// Create = user-authored patterns; My = saved work, appearance and settings.
// Native haptics, purchase, cloud and remote control remain explicitly simulated.
S.ux={tab:'home',open:{},saveRecord:false,patternFilter:'all'};
const UX_TABS=[['home','home','首页'],['music','music','音乐'],['studio','edit','创作'],['my','user','我的']];
const HOME_ROUTES=['home','library','detail','focus','manual'];
const MUSIC_ROUTES=['music','sources','musicauth','analysis','musicplayer','musicmixes','sounds'];
const CREATE_ROUTES=['studio','editor','curve','record','xy','routineedit'];
const uxOldNav=nav;
function uxTabOf(route){return HOME_ROUTES.includes(route)?'home':MUSIC_ROUTES.includes(route)?'music':CREATE_ROUTES.includes(route)?'studio':route==='launch'||route==='onboard'||route==='preferences'||route==='capability'?'home':'my';}
nav=function(route,opts={}){
  // Retain a draft without a compulsory confirmation just to visit another tab.
  // Replacing or deleting it still uses the original confirmation workflow.
  if(['editor','curve'].includes(S.route)&&S.editDirty&&route!==S.route)draftChanged();
  if(S.route==='record'&&route!=='record'&&S.record.events.length){endRecord();try{S.draft=recordToPattern();draftChanged();}catch(e){toast('录制片段仍保留在当前会话。');}}
  S.ux.tab=uxTabOf(route);
  return uxOldNav(route,opts);
};
const UX_COPY={
 p01:['平稳','持续轻触'],p02:['柔绽','轻震、停歇'],p03:['双拍','两次轻点'],p04:['缓浪','慢慢起伏'],p05:['渐起','由轻渐强'],p06:['轻点','稀疏轻触'],
 p07:['连浪','连续起伏'],p08:['涟漪','逐渐减弱'],p09:['阶梯','三档轻重'],p10:['三拍','三次轻点'],p11:['交替','强弱交替'],p12:['留白','较长停歇'],p13:['渐落','渐渐变轻'],p14:['长浪','缓慢变化'],p15:['漂移','轻重错落'],p16:['序列','组合节奏']
};
const uxPattern=()=>S.session?.kind==='pattern'?S.session.pattern:pattern(store.lastPattern||'p02');
const uxPatternLabel=p=>UX_COPY[p.id]?.[0]||p.name;
const uxPatternDesc=p=>UX_COPY[p.id]?.[1]||'自己创作的震感';
const uxHead=(title,caption='',right='')=>`<header class="simple-head"><div><h1>${title}</h1>${caption?`<p>${caption}</p>`:''}</div>${right||`<span class="brand-small">Pulse Loom</span>`}</header>`;
const uxTop=(title,right='')=>`<div class="topbar">${ib('back','back','','返回')}<span class="small">${title}</span><div class="row">${right||'<span style="width:44px"></span>'}</div></div>`;
const uxDetails=(id,title,body)=>`<details class="more-disclosure" data-disclosure="${id}" data-ux-route="${S.route}" ${S.ux.open[S.route+':'+id]?'open':''}><summary>${title}</summary><div class="disclosure-body">${body}</div></details>`;
function uxVisual(kind='pattern',extra=''){
 return `<div class="touch-visual ${extra}" data-touch-kind="${kind}" aria-hidden="true"><div class="touch-art">${art(theme().art)}</div><i class="touch-ring"></i><i class="touch-ring r2"></i><span class="touch-badge">${ic(kind==='music'?'music':'haptic')}</span></div>`;
}
function uxStrength(key,val){return `<div class="simple-strength">${slider('震动强度',key,val)}<div class="range-help"><span>轻</span><span>强</span></div></div>`;}
function uxPresetButton(p){let selected=uxPattern().id===p.id;return `<button class="preset-choice" data-action="uxPick" data-value="${p.id}" aria-pressed="${selected}" aria-label="${esc(uxPatternLabel(p))}，${esc(uxPatternDesc(p))}"><strong>${esc(uxPatternLabel(p))}</strong><small>${esc(uxPatternDesc(p))}</small></button>`;}
function uxPickerRows(items){return items.map(p=>`<div class="preset-list-item"><button class="preset-main ${uxPattern().id===p.id?'selected':''}" data-action="uxPick" data-value="${p.id}"><span class="preset-mini">${pulseMark(p)}</span><span class="grow"><strong>${esc(uxPatternLabel(p))}${p.premium?' <span class="badge pro">Pro</span>':''}</strong><small>${esc(uxPatternDesc(p))}</small></span><span class="check-slot">${uxPattern().id===p.id?ic('check'):''}</span></button>${ib('info','uxPatternInfo',p.id,'查看'+uxPatternLabel(p)+'的详情')}</div>`).join('');}
function uxHome(){const p=uxPattern();return `<div class="page simple-home">
 ${uxHead('震动','选一种喜欢的，轻重随你。')}
 ${uxVisual('pattern')}
 <div class="simple-current"><h2>${esc(uxPatternLabel(p))}</h2><p><i class="state-dot" data-normal-dot></i><span data-normal-state>${uxPatternDesc(p)}</span></p></div>
 <div class="preset-heading"><h3>震动预设</h3><button data-action="sheet" data-value="uxPresets">全部预设 ${ic('arrow')}</button></div>
 <div class="simple-presets">${['p01','p02','p04','p03','p05','p06'].map(id=>uxPresetButton(pattern(id))).join('')}</div>
 ${uxStrength('gain',store.gain)}
 <div class="simple-bottom-actions"><button class="timer-pill" data-action="sheet" data-value="timer" aria-label="定时停止">${ic('clock')}<span data-home-time>${store.timer/60} 分钟后停止</span></button><button data-action="sheet" data-value="adjust">调整触感 ${ic('sliders')}</button></div>
 ${S.guard?`<button class="text-btn" data-action="touchGuard">${ic('lock')}已开启防误触 · 点此解除</button>`:''}
 ${S.output!=='ok'?`<div class="simple-fault">触感暂时不可用。<button data-action="sheet" data-value="fault">查看原因</button></div>`:''}<div class="home-end"></div></div>`;}
VIEWS.launch=()=>`<section class="splash simple-splash"><div class="caps">PERSONAL HAPTIC CARE</div><div><div class="splash-art">${art(theme().art)}</div><div class="logo">Pulse <em>Loom</em></div><h2>把片刻，留给自己。</h2><p>个人震动与触感</p></div><div class="splash-foot">${btn('开始体验','enter')}<div class="helper-text" style="margin-top:15px;font-size:11px;color:var(--muted)">交互模型 · 震动用动画演示</div></div></section>`;
VIEWS.home=uxHome;
VIEWS.onboard=()=>page(`${uxTop('初次使用')}<div class="welcome-art">${art(theme().art)}</div><h1>选好，就可以开始。</h1><p class="lead" style="margin-top:16px">首页选择震动预设；音乐跟随歌曲；创作保存自己的节奏。无需先做设置。</p>${btn('进入首页','finishOnboard')}<div class="gap"></div>${btn('了解触感测试','nav','capability','ghost')}`);
VIEWS.focus=()=>page(`${uxTop('专注震动',ib(S.guard?'lock':'unlock','touchGuard','','防误触'))}<div class="simple-focus"><h1>${esc(uxPatternLabel(uxPattern()))}</h1>${uxVisual('pattern')}<div class="focus-time">还剩 <strong data-live="remaining">${fmt(S.session?.remaining??store.timer)}</strong></div>${S.guard?notice('已锁定调整控件，停止按钮仍然可用。'):uxStrength('gain',store.gain)}<div class="simple-bottom-actions"><button data-action="sheet" data-value="timer">${ic('clock')}定时</button><button data-action="touchGuard">${ic('lock')}${S.guard?'解除防误触':'防误触'}</button></div></div>`);
VIEWS.library=()=>page(`${uxTop('全部震动预设')}<div class="search">${ic('search')}<input id="patternSearch" data-bind="search" type="text" value="${esc(S.search)}" placeholder="搜索预设" aria-label="搜索预设"></div>${seg([['全部','全部'],['免费','免费'],['已收藏','收藏']],S.category,'category')}<div id="libraryResults">${libraryResults()}</div>`);
libraryResults=function(){const p=PRESETS.filter(p=>(!S.search||[p.name,p.en,uxPatternLabel(p),uxPatternDesc(p)].join(' ').toLowerCase().includes(S.search.toLowerCase()))&&(S.category==='全部'||S.category===p.category||S.category==='免费'&&!p.premium||S.category==='已收藏'&&store.favorites.includes(p.id)));return p.length?uxPickerRows(p):empty('没有找到。','换个名称试试。','clearSearch','','清除搜索');};
VIEWS.detail=()=>{const p=pattern(S.detail);return page(`${uxTop('预设详情',ib('heart','favorite',p.id,'收藏',store.favorites.includes(p.id)?'selected':''))}<div class="simple-detail-art">${art(p.art||'flower')}</div><h1>${esc(uxPatternLabel(p))}</h1><p class="lead" style="margin-top:14px">${esc(p.desc||uxPatternDesc(p))}</p><div class="gap"></div>${btn('使用这个预设','uxUsePattern',p.id)}<div class="gap"></div>${btn(S.session?.kind==='preview'?'停止预览':'预览震感','preview',p.id,'outline')}${uxDetails('patternDetails','更多操作',`${drawWave(p)}<p class="small muted">每轮 ${sec(patternLength(p))} · ${patternType(p)}</p>${btn('复制后编辑','editPattern',p.id,'secondary')}${btn('导出节奏文件','exportPattern',p.id,'outline')}`)}`);};
function uxMusicOptions(){const m=S.music;return `<div><div class="simple-sheet-label">音乐位置</div><input type="range" id="musicSeek" data-bind="musicSeek" min="0" max="${m.duration}" step=".1" value="${m.offset}" aria-label="音乐播放进度"></div>${slider('音乐音量','m_volume',m.config.volume)}${slider('跟随灵敏度','m_sensitivity',m.config.sensitivity)}<div><div class="simple-sheet-label">跟随方式</div>${seg([['energy','随起伏'],['beats','跟重拍'],['blend','叠加预设']],m.config.mapping,'musicMapping')}</div><div><div class="simple-sheet-label">触感细节</div>${seg([['smooth','柔和'],['pulse','脉冲'],['crisp','清晰']],m.config.texture,'musicTexture')}</div>${m.config.mapping==='blend'?`<div class="field"><label for="overlay">叠加的预设</label><select id="overlay" data-bind="musicOverlay">${PRESETS.map(p=>`<option value="${p.id}" ${m.config.overlay===p.id?'selected':''}>${esc(uxPatternLabel(p))}</option>`).join('')}</select></div>${slider('预设比例','m_overlayMix',m.config.overlayMix)}`:''}${btn('同步微调与播放区间','sheet','musicAdvanced','outline')}${btn('使用默认触感','uxResetMusic','','ghost')}`;}
function uxMusic(){const m=S.music;let head=uxHead('随音乐震动','选一首歌，让触感跟着走。');
 if(m.status==='loading')return `<div class="page simple-music">${head}<div class="music-loading"><div class="spinner"></div><h2>正在准备音乐</h2><p>${esc(m.name)}</p><p>准备好后即可开始，无需设置。</p></div>${btn('取消','cancelAnalysis','','outline')}</div>`;
 if(!m.buffer)return `<div class="page simple-music">${head}<div class="music-empty-hero">${uxVisual('music')}<h2>你的音乐，你的震感。</h2><p>选择后，自动准备好跟随节奏。</p></div>${m.status==='error'?`${notice(esc(m.error),'error')}<div class="gap"></div>`:''}${btn(ic('plus')+' 选择音乐','importMusic')}<p class="helper-text">从手机或电脑选择音频文件，仅在本机读取。</p><button class="example-start" data-action="demoMusic" data-value="petals">${ic('music')}先用示例试试</button>${uxDetails('sources','其他音乐来源',`${btn('Apple Music / 系统音乐库','nav','musicauth','outline')}<p class="small muted">系统音乐库目前仅演示授权流程，不读取受保护歌曲。</p>${btn('试另一段示例','demoMusic','mist','ghost')}`)}</div>`;
 const feel=uxCurrentFeel();return `<div class="page simple-music">${head}${uxVisual('music','music-active-art')}<div class="simple-current"><h2>跟着喜欢的节奏。</h2><p><i class="state-dot" data-music-dot></i><span data-music-state>音乐已准备好</span></p></div><div class="simple-track"><span class="track-mark">${ic('music')}</span><div class="grow"><h3 title="${esc(m.name)}">${esc(m.name)}</h3><p><span data-live="musicPosition">${fmt(m.offset)}</span> / ${fmt(m.duration)}</p></div><button class="text-btn" data-action="importMusic">换一首</button></div><div class="feel-label">喜欢怎样的触感</div>${seg([['gentle','柔和'],['balanced','均衡'],['clear','鲜明']],feel,'uxMusicFeel')}${uxStrength('m_gain',m.config.gain)}<p class="sound-note">开始后会播放音乐，震动以动画演示。</p><div class="track-tools"><button class="text-btn" data-action="saveMix">${ic('heart')}保存搭配</button><button class="text-btn" data-action="nav" data-value="musicmixes">已存搭配 ${ic('arrow')}</button></div>${uxDetails('musicAdjust','更多调整（可不设置）',uxMusicOptions())}</div>`;
}
VIEWS.music=uxMusic;
VIEWS.musicplayer=uxMusic;
VIEWS.analysis=uxMusic;
VIEWS.sources=()=>page(`${uxTop('选择音乐')}${btn('从文件选择音乐','importMusic')}<div class="gap"></div>${btn('先用示例试试','demoMusic','petals','secondary')}<div class="gap"></div>${btn('Apple Music / 系统音乐库','nav','musicauth','ghost')}<p class="small muted">这条扩展路径保留供审查。平常在音乐页点“选择音乐”就会打开文件选择器。</p>`);
function uxCurrentFeel(){let c=S.music.config;if(c.mapping==='energy'&&c.texture==='smooth'&&c.sensitivity===35)return 'gentle';if(c.mapping==='energy'&&c.texture==='smooth'&&c.sensitivity===55)return 'balanced';if(c.mapping==='beats'&&c.texture==='crisp'&&c.sensitivity===70)return 'clear';return 'custom';}
VIEWS.studio=()=>`<div class="page simple-create">${uxHead('创作','把喜欢的触感，做成自己的。')}<div class="creation-hero"><div class="creation-art">${art('flower')}</div><h2>敲出自己的节奏。</h2><p>轻点或按住，录下指尖的节奏。</p>${btn('开始敲击创作','newDraft','record')}</div>${store.draft?`<div class="gap"></div>${btn('继续未完成的草稿','resumeDraft','','outline')}`:''}<h3 class="simple-subheading">也可以这样创作</h3><div class="create-methods">${[['curve','wave','画出变化','画一条线，改变轻重。'],['basic','sliders','逐段编排','安排每一段的震动与停顿。'],['xy','touch','跟随手指','移动手指，同时调节轻重和质感。']].map(([mode,ico,title,desc])=>`<button class="create-method" data-action="newDraft" data-value="${mode}">${ic(ico)}<span class="grow"><strong>${title}</strong><small>${desc}</small></span><span class="chevron">›</span></button>`).join('')}</div><div class="simple-bottom-actions"><button data-action="nav" data-value="saved">我的作品 ${ic('arrow')}</button><button data-action="nav" data-value="routines">组合多个预设 ${ic('arrow')}</button></div></div>`;
VIEWS.record=()=>{const r=S.record,has=r.events.length>0;return `<div class="page simple-record">${uxTop('敲击创作',ib('info','sheet','recordHelp','录制帮助'))}<h1>${r.active?'轻点，或按住。':has?'这就是你的节奏。':'用手指，做一段节奏。'}</h1><p class="lead" style="margin:10px 0 0">${r.active?'松手后留白，再按下继续。':has?'先预览，再给它起个名字。':'点“开始录制”，再触碰下面的圆。'}</p><button class="record-pad ${r.down!==null?'pressed':''}" id="recordPad" aria-label="节奏录制区域，支持空格键">${ic('touch')}<strong>${r.active?'在这里敲击':has?'已录下 '+r.events.length+' 段':'指尖落在这里'}</strong><small>${r.active?'按住就持续，松手就停':'只记录触碰，不使用麦克风'}</small></button><div class="record-time" data-live="recordTime">${fmt(r.elapsed)}</div><div class="record-count" data-live="recordCount">${r.events.length} 段 · 最长30秒</div><div class="record-main-actions">${r.active?btn('结束录制','recordToggle'):has?`<div class="two">${btn(S.session?.kind==='preview'?'停止预览':'预览','recordPreview','','outline')}${btn('保存节奏','uxSaveRecord')}</div>`:btn('开始录制','recordToggle')}</div><div class="record-secondary">${has?`<button data-action="recordReset">重新录制</button><button data-action="recordUse">再微调一下</button>`:''}${r.active?`<button data-action="recordUndo">撤销上一段</button>`:''}</div></div>`;};
const uxFullEditor=editorView,uxFullCurve=curveView;
function uxAdvancedBlock(d){return `${slider('触感：柔和 → 清晰','e_sharp',Math.round((d.segments[S.selected]?.sharp??.25)*100))}${toggle('循环','到定时结束时停止。','draftLoop',d.loop)}<div class="editor-tools">${ib('undo','undo','','撤销')}${ib('redo','redo','','重做')}${ib('up','moveSegment','-1','前移片段')}${ib('down','moveSegment','1','后移片段')}<button class="text-btn" data-action="zoom">${S.zoom}× 时间轴</button></div><div class="number-row">${numField('渐入时间','fadeIn',d.fadeIn||0,0,5000,'毫秒')}${numField('渐出时间','fadeOut',d.fadeOut||0,0,5000,'毫秒')}</div>${btn('用敲击重新录制','nav','record','outline')}${btn('转换为曲线副本','toCurve','','outline')}`;}
editorView=function(){let d=S.draft||newDraft('basic',true);if(d.mode==='curve')return curveView();let es=d.segments||[];S.selected=Math.min(S.selected,Math.max(0,es.length-1));let e=es[S.selected];return `<div class="page simple-editor">${uxTop('逐段编排',`<button class="text-btn" data-action="saveDraft">保存</button>`)}<div class="field"><label for="draftName">给它一个名字</label><input id="draftName" type="text" maxlength="30" data-bind="draftName" value="${esc(d.name)}" placeholder="我的节奏"></div><div class="timeline-wrap"><div class="timeline" style="width:${S.zoom*100}%">${es.map((v,i)=>`<button class="event-bar ${i===S.selected?'active':''}" data-action="segmentSelect" data-value="${i}" style="flex:${Math.max(50,v.duration+v.gap)};height:${18+v.gain*35}px" aria-label="选择第${i+1}段"><span>${i+1}</span></button>`).join('')}</div></div><div class="segment-number"><span>第 ${S.selected+1} 段 <span class="small muted">/ ${es.length}</span></span><span class="small muted" data-ux-total>总长 ${sec(patternLength(d))}</span></div><div class="editor-tools"><button class="text-btn" data-action="addSegment">${ic('plus')}加一段</button><button class="text-btn" data-action="duplicateSegment">${ic('copy')}复制</button><button class="text-btn" data-action="deleteSegment">${ic('trash')}删除</button></div>${e?`${slider('这一段的强度','e_gain',Math.round(e.gain*100))}<div class="second-fields"><div><label for="uxDuration">震动多久（秒）</label><input id="uxDuration" type="number" min=".05" max="${d.mode==='recorded'?10:2}" step=".05" data-ux-number="duration" value="${+(e.duration/1000).toFixed(3)}"></div><div><label for="uxGap">停顿多久（秒）</label><input id="uxGap" type="number" min="0" max="${d.mode==='recorded'?30:5}" step=".05" data-ux-number="gap" value="${+(e.gap/1000).toFixed(3)}"></div></div>`:btn('添加第一个片段','addSegment','','secondary')}<div id="editorError" class="editor-error">${esc(validatePattern(d))}</div><div class="editor-footer">${btn('预览震感','previewDraft','','outline')}${btn('保存节奏','saveDraft')}</div>${uxDetails('segmentAdvanced','更多编辑选项',e?uxAdvancedBlock(d):'')}<div class="gap"></div>${btn('取消 / 草稿选项','sheet','leaveEditor','ghost')}</div>`;};
curveView=function(){let d=S.draft;if(!d||d.mode!=='curve')d=newDraft('curve',true);return `<div class="page simple-editor">${uxTop('画出变化',`<button class="text-btn" data-action="saveDraft">保存</button>`)}<div class="field"><label for="draftName">给它一个名字</label><input id="draftName" type="text" maxlength="30" data-bind="draftName" value="${esc(d.name)}" placeholder="我的曲线"></div><p class="small muted" style="margin-top:16px">往上更强，往下更轻。拖动圆点改变触感。</p><div class="curvebox">${curveSvg(d)}</div><div class="editor-tools">${ib('undo','undo','','撤销')}${ib('redo','redo','','重做')}<button class="text-btn" data-action="addNode">加一个点</button><button class="text-btn" data-action="deleteNode" data-value="${S.nodeSelected}">删除选中点</button></div>${seg([['wave','起伏'],['rise','渐强'],['fall','渐弱']],d.curveTemplate||'wave','curveTemplate')}<div class="editor-footer">${btn('预览震感','previewDraft','','outline')}${btn('保存曲线','saveDraft')}</div><div id="editorError" class="editor-error">${esc(validatePattern(d))}</div>${uxDetails('curveAdvanced','精细调整',`${numField('整段时长','curveLength',d.cycle/1000,.1,30,'秒')}${slider('触感：柔和 → 清晰','curveSharp',Math.round((d.sharp??.25)*100))}${toggle('循环','到定时结束时停止。','draftLoop',d.loop)}<div class="number-row">${numField('渐入时间','fadeIn',d.fadeIn||0,0,5000,'毫秒')}${numField('渐出时间','fadeOut',d.fadeOut||0,0,5000,'毫秒')}</div><p class="small muted">各点的位置 · 时间（毫秒）/ 强度（%）</p>${d.nodes.map((n,i)=>`<div class="node-row"><span>${i+1}</span><input type="number" min="0" max="${d.cycle}" value="${Math.round(n.time)}" data-node-field="time" data-index="${i}" aria-label="节点${i+1}时间"><input type="number" min="0" max="100" value="${Math.round(n.value*100)}" data-node-field="value" data-index="${i}" aria-label="节点${i+1}强度">${ib('trash','deleteNode',i,'删除节点')}</div>`).join('')}`)}${btn('取消 / 草稿选项','sheet','leaveEditor','ghost')}</div>`;};
VIEWS.editor=()=>editorView();VIEWS.curve=()=>curveView();
VIEWS.my=()=>`<div class="page simple-my">${uxHead('我的','把喜欢的留下来。',ib('settings','nav','settings','设置'))}<div class="my-shortcuts"><button data-action="nav" data-value="saved">${ic('edit')}<strong>我的作品</strong><small>${store.custom.length}</small></button><button data-action="nav" data-value="favorites">${ic('heart')}<strong>收藏</strong><small>${store.favorites.length}</small></button></div><div class="preset-heading"><h3>喜欢的外观</h3><button data-action="nav" data-value="themes">全部主题 ${ic('arrow')}</button></div><div class="simple-theme-pair">${THEMES.slice(0,2).map(t=>`<button data-action="quickTheme" data-value="${t.id}" aria-pressed="${store.theme===t.id}"><i style="background:linear-gradient(135deg,${palette(t.id)[9]},${palette(t.id)[11]})"></i><strong>${t.cn}</strong>${store.theme===t.id?ic('check'):''}</button>`).join('')}</div><div class="simple-group">${linkrow('组合与更多体验','组合、手动、呼吸、远程控制','leaf','nav','methods')}${linkrow('我的音乐搭配','保存的音乐跟随参数','music','nav','musicmixes')}${linkrow('使用记录','由你决定是否保留','clock','nav','history')}</div><button class="membership-link" data-action="nav" data-value="premium">${ic('star')}<span>Pulse Loom Pro</span><span>${store.pro?'已开启体验':'查看权益'} ›</span></button><button class="review-entry" data-action="nav" data-value="review">模型说明与审查</button></div>`;
VIEWS.methods=()=>page(`${uxTop('组合与更多体验')}<div class="simple-group">${linkrow('组合体验','把几个预设接在一起','list','nav','routines')}${linkrow('手动震动','按住感受，松手就停','touch','nav','manual')}${linkrow('呼吸与轻触','跟随自己的舒适节奏','breath','nav','breath')}${linkrow('背景声景','雨声与柔和的合成音','volume','nav','sounds')}</div><h3 class="simple-subheading">连接与快捷方式</h3><div class="simple-group">${linkrow('远程控制','双方确认后，共享一次体验 · 模拟','link','nav','remote')}${linkrow('Apple Watch','在手腕上控制 · 模拟','watch','nav','watch')}${linkrow('桌面组件','常用模式的快捷入口 · 模拟','grid','nav','widgets')}${linkrow('云同步','备份作品、处理冲突 · 模拟','cloud','nav','sync')}</div>`);
VIEWS.settings=()=>page(`${uxTop('设置')}<div class="simple-group">${linkrow('主题与外观','默认跟随系统，也可固定浅色或深色','leaf','nav','themes')}${linkrow('使用记录','选择是否记录每次体验','clock','nav','history')}${linkrow('隐私与数据','备份、恢复、删除本地内容','shield','nav','privacy')}${linkrow('使用帮助','操作说明与常见问题','info','nav','help')}</div><div class="simple-group">${linkrow('Pro 与恢复购买','查看权益和恢复记录','star','nav','premium')}${linkrow('设备与触感','设备测试、故障说明','haptic','nav','capability')}</div>${uxDetails('preferences','其他偏好',`${toggle('使用时保持亮屏','只展示偏好，不改变浏览器的休眠设置。','keepAwake',store.keepAwake)}${toggle('减少动态效果','演示偏好；也会遵循浏览器系统设置。','reduced',store.reduced)}${toggle('大字号试阅','用于检查界面的文字可读性。','largeText',store.largeText)}${toggle('离开时遮盖内容','页面不可见时先暂停。','privacyCover',store.privacyCover)}`)}${btn('关于这份交互模型','nav','review','ghost')}`);
VIEWS.themes=()=>page(`${uxTop('主题与外观')}<h3 class="simple-subheading" style="margin-top:0">界面外观</h3>${appearanceControls()}<div class="gap"></div><div class="theme-grid">${THEMES.map(t=>themeCard(t)).join('')}</div><div class="gap"></div>${btn('更换应用图标','nav','icons','ghost')}`);
VIEWS.themepreview=()=>{const t=theme(S.themePreview);return page(`${uxTop('主题预览')}<h1>${t.cn}</h1><p class="lead" style="margin-top:10px">${t.desc}</p><div class="theme-preview"><div class="simple-head"><h2>震动</h2><span class="brand-small">Pulse Loom</span></div>${uxVisual('preview')}<div class="simple-current"><h2>柔绽</h2><p>轻震、停歇</p></div><div class="simple-presets">${['平稳','柔绽','缓浪'].map((n,i)=>`<span class="preset-choice" aria-hidden="true" style="background:${i===1?'var(--tint)':'var(--surface)'}"><strong>${n}</strong></span>`).join('')}</div><div class="preview-controls"><span>${ic('power')}开始震动</span><span>${ic('stop')}停止</span></div></div>${btn(store.theme===t.id?'已应用 · 返回':'应用这套主题','applyTheme',t.id)}<div class="gap"></div>${btn('取消预览','cancelTheme','','ghost')}`);};
VIEWS.premium=()=>`<div class="page simple-pro">${uxTop('Pro',`<button class="text-btn" data-action="restore">恢复购买</button>`)}<div class="pro-art">${art('flower')}</div><h1>更多属于你的选择。</h1><div class="benefits">${['全部震动预设和主题','完整歌曲的触感跟随','保存更多自创与组合'].map(t=>`<div class="row">${ic('check')}<span>${t}</span></div>`).join('')}</div><div class="price-card"><strong>$9.99</strong><p>一次性买断示例 · 无自动续费</p></div>${btn(store.pro?'已开启 · 体验购买流程':'体验解锁 Pro','purchaseMock','success')}<p class="pro-footnote">此处是购买流程演示，没有实际扣费。原型默认开放全部功能，方便审查。</p>${uxDetails('purchaseTesting','审查购买结果',`${btn(store.pro?'切换到免费用户':'开启完整体验','togglePro','','outline')}<div class="three">${btn('取消','purchaseMock','cancel','secondary')}${btn('待批准','purchaseMock','pending','secondary')}${btn('失败','purchaseMock','error','secondary')}</div>${btn('模拟退款撤销','revoke','','ghost')}${btn('条款与隐私','sheet','terms','ghost')}`)}</div>`;
// Minimal task-specific sheets. Presets and standard timers apply immediately.
const uxBaseSheet=renderSheet;
function uxSheetHTML(title,body){return `<div class="modal-shade" data-dismiss="true"><section class="sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="topbar"><h2>${title}</h2>${ib('close','closeSheet','','关闭弹层')}</div>${body}</section></div>`;}
renderSheet=function(){if(!S.modal)return uxBaseSheet();const {type}=S.modal;let title,body;
 if(type==='uxPresets'||type==='hapticPatterns'){title='选择震动预设';let list=S.ux.patternFilter==='saved'?store.custom:PRESETS;body=`${seg([['all','预设'],['saved','我的作品']],S.ux.patternFilter,'uxPatternFilter')}<div class="simple-presets-sheet">${list.length?uxPickerRows(list):'<p class="small muted" style="padding:25px 0">还没有作品，可以从“创作”录下一段。</p>'}</div>`;}
 else if(type==='timer'){title='多久后停止';body=`<p class="small muted">选好就会生效，到时自动停止。</p><div class="simple-time-choices">${[60,180,300,600].map(t=>`<button data-action="uxTimer" data-value="${t}" aria-pressed="${store.timer===t}">${t/60} 分钟</button>`).join('')}</div>${uxDetails('customTimer','自定义时长',`${numField('时长','timerInput',S.timerInput||store.timer,30,600,'秒')}${btn('使用这个时长','timerApply')}`)}`;}
 else if(type==='adjust'){title='调整触感';body=`<p class="simple-sheet-label">节奏快慢</p>${seg([['.7','慢一点'],['1','原速'],['1.4','快一点']],String(store.speed),'uxSpeed')}<p class="simple-sheet-label">触感质地</p>${seg([['15','柔和'],['45','均衡'],['80','清晰']],String(store.sharp),'uxSharp')}${uxDetails('fineAdjust','精细调节',`${slider('震动强度','gain',store.gain)}${slider('节奏速度','speed',store.speed,.5,2,.1,'×')}${slider('触感质地','sharp',store.sharp)}`)}<div class="gap"></div>${btn('完成','closeSheet')}${btn('恢复默认触感','resetAdjust','','ghost')}`;}
 else if(type==='uxRecordName'){title='保存这段节奏';body=`<label class="simple-sheet-label" for="uxRecordName">名称</label><input id="uxRecordName" type="text" maxlength="30" value="${esc(S.draft?.name||'我的节奏')}" placeholder="我的节奏"><div class="gap"></div>${btn('保存到我的作品','uxCommitRecord')}`;}
 if(title){$('#modalRoot').innerHTML=uxSheetHTML(title,body);if(S.session?.playing||S.music.playing||S.sound.active)$('#modalRoot .sheet').insertAdjacentHTML('beforeend',`<div class="sheet-emergency">${btn(ic('stop')+' 立即停止','stop','','outline')}</div>`);}
 else uxBaseSheet();
};
ACTIONS.uxTab=route=>{if(!UX_TABS.some(t=>t[0]===route))return;nav(route,{reset:true});};
ACTIONS.uxPatternFilter=v=>{S.ux.patternFilter=v;renderSheet();};
ACTIONS.uxPatternInfo=v=>{closeSheet();S.detail=v;nav('detail');};
ACTIONS.uxPick=v=>{if(S.guard)return toast('先解除防误触');const p=pattern(v);const run=()=>{selectPattern(v);if(S.session?.kind==='pattern'){let used=elapsed(S.session);S.session.pattern=p;S.session.title=p.name;S.session.elapsed=used;S.session.anchor=performance.now();S.session.remaining=Math.max(0,S.session.limit-used);}if(S.modal)closeSheet();if(S.route==='library')nav('home');else render();};if(p.premium&&!store.pro)return gate('这是 Pro 预设。','可以先预览，当前选择会保留。',run);run();};
ACTIONS.uxUsePattern=v=>{const p=pattern(v);const run=()=>{ACTIONS.uxPick(v);nav('home',{reset:true});};if(p.premium&&!store.pro)return gate('这是 Pro 预设。','选择其他预设也可以开始。',run);run();};
ACTIONS.uxHomeStart=()=>{S.homeSource='pattern';const p=uxPattern();if(S.session?.kind==='pattern'){if(S.music.playing)pauseMusic();return resumeSession();}startSession(p,'pattern');};
ACTIONS.uxTimer=v=>{S.timerInput=Number(v);ACTIONS.timerApply();};
ACTIONS.uxSpeed=v=>{store.speed=Number(v);if(S.session)S.session.speed=store.speed;persist();renderSheet();};
ACTIONS.uxSharp=v=>{store.sharp=Number(v);persist();renderSheet();};
ACTIONS.uxMusicFeel=v=>{const set={gentle:{sensitivity:35,texture:'smooth',mapping:'energy'},balanced:{sensitivity:55,texture:'smooth',mapping:'energy'},clear:{sensitivity:70,texture:'crisp',mapping:'beats'}}[v];if(!set)return;Object.assign(S.music.config,set);render();};
ACTIONS.uxResetMusic=()=>{const m=S.music;Object.assign(m.config,{sensitivity:55,texture:'smooth',mapping:'energy',offset:0,overlay:'none',overlayMix:25,from:0,to:m.duration});render();toast('已恢复默认触感');};
ACTIONS.uxSaveRecord=()=>{endRecord();if(!S.record.events.length)return toast('先录下一段节奏');showSheet('uxRecordName');};
ACTIONS.uxCommitRecord=()=>{const n=$('#uxRecordName')?.value.trim();if(!n||[...n].length>30)return toast('请输入1–30个字的名称');closeSheet();ACTIONS.recordUse();if(S.route!=='editor'||!S.draft)return;S.draft.name=n;draftChanged();saveDraft();};
// Keep all existing advanced branches, but no modal is a prerequisite for the common path.
const uxOldQuick=ACTIONS.quickPattern;
ACTIONS.quickPattern=v=>ACTIONS.uxPick(v);
const uxOldPlay=ACTIONS.play;
ACTIONS.play=()=>['home','focus'].includes(S.route)?ACTIONS.uxHomeStart():uxOldPlay();
const uxOldMusicPlay=ACTIONS.musicPlay;
ACTIONS.musicPlay=()=>playMusic();
const uxOldReset=ACTIONS.resetPrototype;
ACTIONS.resetPrototype=()=>{uxOldReset();const run=confirmation?.run;if(run)confirmation.run=()=>{S.ux={tab:'home',open:{},saveRecord:false,patternFilter:'all'};run();};};
// Update primary control by task, not by whichever media happens to be active.
const uxOriginalDock=renderHapticDock;
renderHapticDock=function(){const el=$('#hapticDock');let route=S.route,isHome=['home','focus'].includes(route),isMusic=['music','musicplayer','analysis'].includes(route)&&S.music.status==='ready'&&S.music.buffer;
 if(route==='manual')return uxOriginalDock();
 if(!isHome&&!isMusic){el.hidden=true;el.innerHTML='';return;}
 el.hidden=false;let playing=isHome?S.session?.kind==='pattern'&&S.session.playing:S.music.playing;let paused=isHome?S.session?.kind==='pattern'&&!S.session.playing:S.music.offset>0;
 let label=isHome?(playing?'暂停震动':paused?'继续震动':'开始震动'):(playing?'暂停跟随':paused?'继续跟随':'开始跟随');
 el.innerHTML=`<div class="haptic-dock-controls"><button class="haptic-start" data-action="${isHome?'uxHomeStart':'musicPlay'}" aria-label="${label}">${ic(playing?'pause':'power')}<span>${label}</span></button><button class="haptic-stop" data-action="stop" aria-label="停止全部输出">${ic('stop')}<span>停止</span></button></div>`;
};
renderMini=function(){const output=S.music.playing?'music':S.session?.playing?'pattern':S.sound.active?'sound':null;const r=S.route;const musicVisible=['music','musicplayer','analysis'].includes(r);const homeVisible=['home','focus','manual'].includes(r)&&S.session?.kind==='pattern';
 if(!output||['launch','onboard','preferences','capability'].includes(r)||output==='music'&&musicVisible||output==='pattern'&&(homeVisible||['routineplayer','breathplayer','manual','record','xy'].includes(r))||output==='sound'&&r==='sounds'){$('#mini').innerHTML='';return;}
 const target=output==='music'?'music':output==='sound'?'sounds':S.session?.kind==='routine'?'routineplayer':S.session?.kind==='breath'?'breathplayer':S.session?.kind==='manual'?'manual':'home';
 const title=output==='music'?'音乐跟随进行中':output==='sound'?'背景声音进行中':S.session?.kind==='preview'?'正在预览震感':'震动进行中';
 $('#mini').innerHTML=`<div class="mini-player">${ic(output==='music'?'music':output==='sound'?'volume':'haptic')}<button class="mini-name" data-action="nav" data-value="${target}">${title}<span class="tiny">${output==='music'?esc(S.music.name):esc(S.session?.title||'点击返回')}</span></button>${ib('stop','stop','','停止全部输出')}</div>`;
};
const uxBaseRender=originalRender; // Original full engine render, avoiding old tab priorities.
render=function(){const container=$('#app');const previous=container.dataset.route;const oldScroll=container.scrollTop;
 $$('details[data-disclosure]').forEach(el=>{S.ux.open[el.dataset.uxRoute+':'+el.dataset.disclosure]=el.open;});
 uxBaseRender();container.dataset.route=S.route;$('#device').dataset.route=S.route;
 const selected=uxTabOf(S.route);$('#tabs').innerHTML=UX_TABS.map(([r,ico,t])=>`<button data-action="uxTab" data-value="${r}" class="${selected===r?'active':''}" ${selected===r?'aria-current="page"':''} aria-label="${t}">${ic(ico)}<span>${t}</span></button>`).join('');
 $('#prototypeLabel').textContent='交互模型 · 震动为动画演示';
 // Keep reviewer controls outside the everyday app surface. They remain reachable in My.
 $('#prototypeLabel').style.cursor='default';
 renderHapticDock();renderMini();uxUpdate();
 $$('input[type="range"]').forEach(uxPaintRange);
 if(previous===S.route)container.scrollTop=oldScroll;
};
function uxPaintRange(el){if(!el)return;let min=Number(el.min)||0,max=Number(el.max)||100;el.style.setProperty('--range-fill',Math.round((Number(el.value)-min)/(max-min)*100)+'%');}
function uxUpdate(){const regular=S.session?.kind==='pattern',normalRunning=regular&&S.session.playing,musicRunning=S.music.playing;
 $$('[data-touch-kind]').forEach(el=>{const kind=el.dataset.touchKind;const run=kind==='pattern'?normalRunning:kind==='music'?musicRunning:false;el.classList.toggle('running',!!run);if(!store.reduced)el.style.setProperty('--touch-level',String(run?(kind==='music'?mappedLevel():requestedPatternLevel()):0));});
 $$('[data-normal-state]').forEach(el=>el.textContent=normalRunning?'震动中':regular?'已暂停':uxPatternDesc(uxPattern()));
 $$('[data-normal-dot]').forEach(el=>el.classList.toggle('active',!!normalRunning));
 $$('[data-music-state]').forEach(el=>el.textContent=musicRunning?'正在跟随音乐':S.music.offset>0?'已暂停':'音乐已准备好');
 $$('[data-music-dot]').forEach(el=>el.classList.toggle('active',!!musicRunning));
 $$('[data-home-time]').forEach(el=>el.textContent=regular?`还剩 ${fmt(S.session.remaining)}`:`${store.timer%60===0?store.timer/60+' 分钟':store.timer+' 秒'}后停止`);
}
const uxBaseLive=updateLive;
updateLive=function(){uxBaseLive();uxUpdate();};
// Preserve expansion state through input changes, without persisting reviewer configuration.
document.addEventListener('toggle',e=>{let el=e.target;if(el.isConnected&&el.matches?.('details[data-disclosure]'))S.ux.open[el.dataset.uxRoute+':'+el.dataset.disclosure]=el.open;},true);
document.addEventListener('input',e=>{if(e.target.matches('input[type="range"]'))uxPaintRange(e.target);});
document.addEventListener('change',e=>{let key=e.target.dataset.uxNumber;if(!key||!S.draft?.segments?.[S.selected])return;let value=Number(e.target.value);if(!Number.isFinite(value)||value<Number(e.target.min)||value>Number(e.target.max)){e.target.value=S.draft.segments[S.selected][key]/1000;toast('时长超出范围，已保留原值');return;}remember();S.draft.segments[S.selected][key]=Math.round(value*1000);draftChanged();uxUpdateEditor();});
// One-page music preparation: asynchronous decode returns to the same task, never autoplay.
// Legacy analysis/source screens remain available in the reviewer map for edge cases.
for(const s of SCREENS){const map={home:['普通震动首页','选择预设 → 开始 → 直接调强度'],music:['音乐','选歌 → 自动准备 → 开始跟随'],studio:['创作','敲击 / 绘制 / 编排 → 预览 → 保存'],my:['我的','作品 / 收藏 / 主题 / 更多体验'],library:['全部预设','点选即生效，无需经过详情'],musicplayer:['音乐跟随','歌曲已就绪，与音乐页使用同一套控件']};if(map[s[0]]){s[2]=map[s[0]][0];s[4]=map[s[0]][0];s[5]=map[s[0]][1];}}
// Short, task-oriented copy for the existing collection pages.
VIEWS.saved=()=>page(`${uxTop('我的作品',ib('plus','nav','studio','开始创作'))}${store.custom.length?`<div class="simple-save-list">${store.custom.map(p=>`<div class="list-row"><span class="preset-mini">${pulseMark(p)}</span><button class="list-link" data-action="detail" data-value="${p.id}"><h4>${esc(p.name)}</h4><p>${p.mode==='curve'?'绘制':p.mode==='recorded'?'录制':'编排'} · ${sec(patternLength(p))}</p></button>${ib('dots','manage',p.id,'管理作品')}</div>`).join('')}</div>`:empty('留下一段自己的节奏。','录下或画出触感，在这里随时找到。','nav','studio','开始创作')}${uxDetails('files','导入与导出',`${btn('从文件导入作品','importPattern','','outline')}${btn('导出全部作品','exportLibrary','','outline')}<p class="small muted">免费可存3个作品，Pro可存200个。备份文件保存在你选择的位置。</p>`)}`);
VIEWS.favorites=()=>page(`${uxTop('收藏')}<p class="lead" style="margin:0 0 12px">把常用的震感放在一起。</p>${store.favorites.length?store.favorites.map(id=>{const p=pattern(id);return `<div class="list-row"><button class="list-link" data-action="detail" data-value="${id}"><h4>${esc(uxPatternLabel(p))}</h4><p>${esc(uxPatternDesc(p))}</p></button>${ib('up','favoriteUp',id,'向上排序')}${ib('heart','favorite',id,'取消收藏','selected')}</div>`}).join(''):empty('还没有收藏。','在预设详情中点心形即可收藏。','nav','library','浏览预设')}`);
VIEWS.musicmixes=()=>page(`${uxTop('音乐搭配')}<p class="lead" style="margin:0 0 12px">保存喜欢的触感。自己的音乐下次需重新选择。</p>${store.mixes.length?store.mixes.map(m=>`<div class="list-row">${ic('music')}<button class="list-link" data-action="loadMix" data-value="${m.id}"><h4>${esc(m.name)}</h4><p>${esc(m.track)}</p></button>${ib('trash','deleteMix',m.id,'删除搭配')}</div>`).join(''):empty('留下一种喜欢的搭配。','在音乐页选好触感，点“保存搭配”。','nav','music','去音乐页')}`);
VIEWS.history=()=>page(`${uxTop('使用记录')}${toggle('保留使用记录','默认关闭，开启后仅保存在本机。','historyEnabled',store.historyEnabled)}${store.history.length?store.history.map(h=>`<div class="list-row">${ic(h.kind==='music'?'music':'clock')}<div class="grow"><h4>${esc(h.name)}</h4><p>${new Date(h.at).toLocaleDateString('zh-CN')} · ${fmt(h.seconds)}</p></div></div>`).join(''):`<p class="small muted" style="margin-top:24px">${store.historyEnabled?'开始一次体验后，记录会出现在这里。':'关闭时不新增记录。已有记录不会因关闭而自动删除。'}</p>`}${store.history.length?btn('清空记录','clearHistory','','ghost'):''}`);
VIEWS.help=()=>page(`${uxTop('使用帮助')}${[['怎样开始震动？','首页先选预设，再点“开始震动”。轻重用滑杆调整，停止按钮随时可用。'],['音乐模式在哪里？','底部第二个“音乐”。选择音乐后自动准备，再点“开始跟随”，无需先做参数设置。'],['怎样保存自己的节奏？','进入“创作”，点“开始敲击创作”。录完后可以预览和保存；也能选择绘制或逐段编排。'],['为什么手机没有震动？','这份 HTML 是交互模型，以动画表示震动，没有控制手机马达。音乐和合成声景会在主动开始后真实发声。'],['主题和暗色在哪里？','进入“我的 → 全部主题”。默认随系统，也可以指定浅色或深色。'],['音乐文件和作品存在哪里？','音乐只留在本次浏览器内存，重新打开需要重新选择。作品保存在浏览器本地存储，重要作品可从“我的作品 → 导入与导出”备份。'],['其他完整功能呢？','“我的 → 组合与更多体验”保留组合、手动、呼吸、声景、远控、Watch、组件和同步。远控、同步、购买和原生系统功能仅演示流程。']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}<div class="gap"></div>${btn('触感故障排查','nav','troubleshoot','outline')}${btn('模型说明与全部页面','nav','review','ghost')}`);
const uxOriginalFeedback=VIEWS.feedback;
VIEWS.feedback=()=>uxOriginalFeedback().replace('例如：首页希望更突出音乐入口；某主题标题对比度不足。','例如：音乐页的换歌按钮还不够明显；某个操作需要重复确认。');
// The review map is deliberately separate from the consumer-facing navigation.
const uxOriginalReview=reviewView;
reviewView=function(){let html=uxOriginalReview();return html.replace('六条完整体验路线','四个主页面与扩展体验').replace('预设 → 简单调节 → 定时 → 专注播放','首页：选预设 → 开始震动 → 调轻重').replace('选歌 → 分析 → 音乐同步 → 保存配置','音乐：选歌 → 自动准备 → 开始跟随').replace('分段 / 曲线 / 录制 / XY → 保存 → 管理','创作：敲击 / 绘制 / 编排 → 保存').replace('完整能力都保留在这里','扩展功能集中在我的页面');};
// Parameter commits update the illustration in place. Rebuilding a focused form
// during its blur/change event can swallow the user's subsequent Save tap.
function uxUpdateEditor(){const d=S.draft;if(!d)return;
 if(d.mode==='curve'){
   const box=$('.curvebox');if(box)box.innerHTML=curveSvg(d);
   $$('[data-node-field]').forEach(el=>{const n=d.nodes[Number(el.dataset.index)];if(n&&document.activeElement!==el)el.value=el.dataset.nodeField==='time'?Math.round(n.time):Math.round(n.value*100);});
 }else{
   $$('.event-bar').forEach((el,i)=>{const e=d.segments[i];if(!e)return;el.style.flex=String(Math.max(50,e.duration+e.gap));el.style.height=(18+e.gain*35)+'px';});
   const total=$('[data-ux-total]');if(total)total.textContent='总长 '+sec(patternLength(d));
 }
 $$('input[type=range]').forEach(uxPaintRange);
}
// Protect DOM updates from synchronous re-entrancy caused by browser blur events.
const uxRenderCore=render;let uxRendering=false,uxRerender=false;
render=function(){if(uxRendering){uxRerender=true;return;}uxRendering=true;try{uxRenderCore();}finally{uxRendering=false;if(uxRerender){uxRerender=false;queueMicrotask(()=>render());}}};
const uxSheetCore=renderSheet;let uxSheetRendering=false,uxResheet=false;
renderSheet=function(){if(uxSheetRendering){uxResheet=true;return;}uxSheetRendering=true;try{uxSheetCore();}finally{uxSheetRendering=false;if(uxResheet){uxResheet=false;queueMicrotask(()=>renderSheet());}}};
// Selection highlights already acknowledge these reversible changes. Avoid a
// success toast obscuring Start after the user changes appearance or duration.
const uxToast=toast;
toast=function(message){if(/^(已应用.*皮肤|计时已更新|已恢复默认触感)$/.test(message))return;return uxToast(message);};
